import type { AgentLogEntry, Lab, LabStatus, ProviderStatus, SystemResources } from "@ammarlab/shared";
import { EmptyState } from "../components/EmptyState";
import { LogList } from "../components/LogList";
import { StatusCard } from "../components/StatusCard";
import { providerStateLabel } from "../utils/providerStatus";

export function DashboardPage({ online, providers, resources, labs, logs, runningLab, runningLabTitle, onStart, onStop, onReset, onViewLab, onGoCatalog }: { online: boolean; providers: ProviderStatus[]; resources: SystemResources | null; labs: Lab[]; logs: AgentLogEntry[]; runningLab?: LabStatus; runningLabTitle?: string; onStart: (id: string) => void; onStop: (id: string) => void; onReset: (id: string) => void; onViewLab: (id: string) => void; onGoCatalog: () => void; }) {
  const hyperv = providers.find((p) => p.provider === "hyperv"); const vmware = providers.find((p) => p.provider === "vmware");
  return <section className="page-stack"><article className="glass-panel page hero"><h1>Launch hands-on IT labs locally</h1><p>Practice Windows Server, Active Directory, Linux, PowerShell and networking labs on your own machine using Hyper-V or VMware Workstation.</p><div className="actions"><button onClick={onGoCatalog}>Start a Lab</button></div></article><div className="status-grid"><StatusCard title="Local Agent" value={online ? "Online" : "Offline"} /><StatusCard title="Hyper-V" value={providerStateLabel(hyperv?.state ?? "unknown")} /><StatusCard title="VMware Workstation" value={providerStateLabel(vmware?.state ?? "unknown")} /><StatusCard title="Labs Available" value={String(labs.length)} /></div><article className="glass-panel page"><h3>System Resources</h3><p>{resources ? `${resources.platform} ${resources.osVersion} • CPU: ${resources.cpuModel} (${resources.cpuLogicalCores}) • RAM: ${resources.freeRamGb}/${resources.totalRamGb} GB free • Disk free: ${resources.diskFreeGb ?? "n/a"} GB • Virtualization: ${resources.virtualizationHint}` : "Not available"}</p></article><div className="split-grid"><article className="glass-panel page"><h3>Featured Labs</h3><div className="labs-grid">{labs.slice(0, 3).map((lab) => <div className="lab-card" key={lab.id}><h4>{lab.title}</h4><p>{lab.description}</p><div className="actions"><button onClick={() => onViewLab(lab.id)}>View</button><button className="ghost" onClick={() => onStart(lab.id)}>Start</button></div></div>)}</div></article><article className="glass-panel page"><h3>Current Lab Session</h3>{runningLab ? <><p><strong>{runningLabTitle}</strong> is currently running.</p><div className="actions"><button onClick={() => onStart(runningLab.labId)}>Start</button><button className="ghost" onClick={() => onStop(runningLab.labId)}>Stop</button><button className="ghost" onClick={() => onReset(runningLab.labId)}>Reset</button></div></> : <EmptyState>No active lab session. Start one from the catalog.</EmptyState>}</article></div><article className="glass-panel page"><h3>Recent Activity</h3><LogList logs={logs.slice(0,8)} /></article></section>;
}
